service: synonym 
provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-west-2
  timeout: 1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetRecords
        - dynamodb:GetItem
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
        - "lambda:InvokeFunction"
      Resource:
        - "arn:aws:dynamodb:us-west-2:163792334106:table/${self:provider.stage}-synonyms"
package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  synonym:
    handler: bin/main
    events:
      - http:
          path: synonyms
          method: get
          integration: lambda
          request:
            template:
              #application/json: $input.params
              application/json: '{ "tag" : "$input.params(''tag'')" }'
    memorySize: 128
    cors:
      origins:
        - '*'
      headers:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowCredentials: false
resources:
  Resources:
    SynonymssTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:provider.stage}-synonyms"
        AttributeDefinitions:
          - 
            AttributeName: tag
            AttributeType: S
        KeySchema:
          - 
            AttributeName: tag
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
